### ISSUE TITLE
✏️やりたいことを列挙する

### ISSUE THREAD

**Issue by uknmr** [uknmr/michizane#2]
やりたいことを列挙していきましょう。

最終的に Wiki または README にまとめます。

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/201231034413664/201239764148335)

**Comment by mediba-kanamori** [comment]
Asana と連携してどうしてもバグってしまう Emoji くん(´；ω；｀)

**Comment by mediba-kanamori** [comment]
PWPA に含まれちゃってるけど、 Service Worker

**Comment by mediba-kanamori** [comment]
Firebase Analytics から BigQuery への流し込み

**Comment by hosoyama-mediba** [comment]
一応、Web Push

**Comment by mediba-kanamori** [comment]
よくわかってないけど AdMob 入れてみたい

**Comment by mediba-kanamori** [comment]
サーボレスアーキテクチャも体験しておきたい。
API Gateway + Kinesis + Lambda?
